theme: jekyll-theme-minimal
title: Ruicong Chen (陈睿聪)
description: PhD student at MIT EECS
logo: profile.jpg
author:
  email:         raychen AT mit.edu
  github:        Seraphmcrc
  linkedin:      ruicong-chen-9164a916b/