theme: jekyll-theme-minimal
title: Ruicong Chen (陈睿聪)
description: PhD student at MIT EECS
logo: profile.jpg
author:
  email:         raychen AT mit.edu
  googlescholar: https://scholar.google.com/citations?user=igmp6y0AAAAJ&hl=en
  github:        Seraphmcrc
  linkedin:      ruicong-chen/